README.md

Updates the TOC to reflect the latest changes

Update TOC in the main README

---

spec.bs

Now that the feature is adopted by WebAppSec, the self link is broken.

Update self-link in spec

---

README.md

It's not clear what it means for an API to be "in a secure context" unless we propagate information about the DOM to the network stack. Instead we align with the cookie secure attribute and allow SSL+localhost.

Update description of Secure Contexts

---

deploy.sh
server.js

In order to streamline development, we want people to be able to use a remixed server for staging changes. Creating a remix currently requires modifying .env each time. This commit fixes that and updates deploy.sh to support a staging remote.

Let deploy.sh use multiple remotes

---

server.js
src/pages/index.hbs

This PR:
1. Fixes the CookieExpireTime values so they display the latest values on refresh, and
2. Replaces the CookieExpired column with a new column CookieEverRefreshed.
When the actual browser cookie has its expires field updated, that needs to be updated within the cookies in g_sessions as well for the changes to be reflected in the UI (for the columns CookieExpireTime and CookieExpired).
Once that's true, that makes the CookieExpired column not very useful, because it will always say "false" since a page reload will trigger a refresh and unexpire any expired cookies. So, that column is replaced with a new column displaying whether a cookie's expiry has ever increased (CookieEverRefreshed). It starts out as false, and it gets set to true once a refresh increases the cookie's expiry.

Have cookie expiry changes reflected in UI

---

README.md

Reviewers identified a few key properties DBSC must satisfy in order to uphold the privacy goals listed in the privacy considerations. We now explicitly state them in the explainer.

Update explainer with privacy commitments

---

README.md

This also moves comments related to `include_site` down a line so it's more clear what they're referring to.

Clarify scope origin is an origin (not a host)

---

spec.bs

This adds a lot more detail to the spec. It's still not fully complete and explicit, but at this point it should be a better reference than the explainer.

Flesh out spec

---

CONTRIBUTING.md

DBSC has been adopted by WebAppSec so remove the reference to the CG in CONTRIBUTING.md.

Update contribution file with WebAppSec

---

README.md

While this is called out in the privacy considerations section, it's not clear what "kty-specific parameters" refers to. It's worth reiterating that we do not send the certificate chain in that field.

Clarify that the TPM certificate chain is not sent

---

README.md

The spec says "dbsc+jwt", so we should say that in the explainer too.

Update JWT type in explainer

---

README.md
spec.bs

The spec and explainer do not agree on what keys are in the JWT. This will align them.

Clarify JWT format

---

spec.bs

The refresh endpoint is very sensitive to availability and latency issues. Site owners should be aware of that when adopting DBSC.

Include some server-side recommendations in the spec

---

spec.bs

We don't want to let subdomains register site-scoped sessions without opt-in from the eTLD+1. A .well-known identifer will provide that opt-in.

Specify .well-known URL for subdomain registration

---

spec.bs

This should take a request and a response, so it has an originating request to pass into algo-session-request.
This is a followup on https://github.com/w3c/webappsec-dbsc/pull/123#discussion_r2039789924

Clarify input on algo-create-session

---

spec.bs

When the `origin` field does not contain the scheme, DBSC returns `InvalidScopeOrigin` from `RegistrationResult`.
If the scheme is not required, then this PR should be closed and the implementation itself be updated.

Update spec.bs to origin with scheme

---

README.md
spec.bs

Also updates `Set-Cookie` to include matching `SameSite` value as attribute list

Update to indicate that `HttpOnly` is required for CookieCraving 

---

spec.bs

"continue" and "defer_requests" do not belong in the "scope" dictionary.

Fix key locations in example

---

spec.bs

In order to handle requests covered by multiple sessions, we shouldn't continue the request even after a failed refresh. Instead, we track the sessions that have already deferred the request, and refuse to defer due to the same session multiple times.

Update session selection mechanism

---

spec.bs

In some situations, the browser will intentionally skip refreshing bound credentials. In order for sites to understand if their DBSC session is working correctly, we should indicate which requests were intentionally skipped.

Specify debug header behavior

---

README.md
spec.bs

This addresses https://github.com/w3c/webappsec-dbsc/issues/65. I also relax the "new Sec-Session-Challenge" requirement. This has the advantage of letting Sec-Session-Challenge processing be completely uniform. It only caches a new challenge, and 403 only requests a new signature. Since this section only applies to the refresh endpoint, I believe that sites can make sure they aren't accidentally returning 403 on this one endpoint.

Use 403 instead of 401 for retries

---

spec.bs

This PR makes a series of non-substantive changes that attempt to make
the current intended behavior more clear, including:
- Wording updates
- Fixing algorithm input/output types
- Fixing link destinations

Wording clarifications

---

spec.bs

The specification for host matching is less powerful than currently implemented in Chrome. Chrome seems unspecified, but described [here](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#proxy-bypass-rules). I don't think we want the full power described in that document for DBSC though. The current specification covers the expected key use cases.
Host matching will be reused for `allowed_request_initiators` in a subsequent PR, so it's broken out into its own algorithm.

Specify session scope matching more precisely

---

spec.bs

This PR significantly rewrites the timing side channel section to detail our choices regarding CORS integration. It also introduces a new mechanism, `allowed_refresh_initiators`, to cover non-CORS loads.

Specify timing side-channel solution

---

spec.bs

We were previously fairly vague about the additions and removals to the user agent session store. This PR makes that more clear. This is similar to the handling of
[permissions](https://w3c.github.io/permissions/#permission-store) or the [connection pool](https://fetch.spec.whatwg.org/#connections).

Specify that session store is owned by the user agent

---

spec.bs

This is meaningless on the response headers, and on the Sec-Session-Response, the server needs to carefully validate that the expected key is being used anyway. It does seem kind of nice if the server can trust that the Sec-Session-Id is truly coming from the site instead of an XHR, so that it can look up the right expected public key for the Sec-Session-Response, so we leave the Sec- prefix on that one header. Following the discussion on
https://github.com/w3c/webappsec-dbsc/issues/59, we make the shared prefix Secure-Session- instead.

Remove Sec- prefixes

---

spec.bs

This PR makes a few changes to how we do refreshes. We now only allow refreshes to change the params for the session being refreshed. We also allow refresh endpoints to not serve any config. This PR is also a little stricter with terminating the session on invalid refresh configs.

Only allow refresh of same session

---

spec.bs

This fixes a few places we weren't precise about the types:
- Sites are not the same as registrable domains
- Registrable domains are extracted from hosts
- Origins are same-site, not URLs

Rework type mismatches around origin vs URL vs host

---

spec.bs

The current description doesn't really align with the Fetch redirect handling. While it's nice to ensure that sites don't expose themselves to significant risk, we already require that the refresh URL be HTTPS, so sites need to do significant work to take on this risk. Simpler Fetch integration is valued over protecting sites from themselves.

Update redirect handling for DBSC requests

---

README.md

To emphasize that DBSC does not change cookie inclusion logic, add the word "already" into this.

Replace "whatever_cookies_apply_to_this_request"

---

spec.bs

We don't continue to try to replace the session if "continue" is false.

Add "and return" when terminating session

---

spec.bs

To avoid using the DBSC session parameters or cached challenge as a cross-site information leak, we require that it only be used in contexts that could set a bound cookie anyway.

DBSC state should only update when cookies can be set

---

spec.bs

We did not define those fields on the device bound session. Update the dfns and links appropriately.

Fix links to session scope and session credentials

---

spec.bs

Sites shouldn't have to specify both domain and path in every scope rule. By default, these should always match.
On the other hand, sites should have to specify include_site. A boolean value isn't too hard to declare, and this lets us make the field optional later with slightly different semantics (folding it into `session_inclusion_rules`)

Change some field defaults

---

spec.bs

Based on some early feedback, make a few changes to the key sharing section:
- Minimize use of the term IdP, since DBSC is not tied deeply to identity (just cookies)
- Require links from RP to SP to avoid one RP unmasking users between multiple SPs
- Add a link to the permissions spec where it is explicit that browsers can mediate this with UX

Improve key sharing section

---

server.js

This allows developers to test without overriding the OT integration, giving us more assurance the OT integration is working as intended.

Add Origin Trial token to DBSC test server

---

spec.bs

We should explicitly mention somewhere that browser-initiated DBSC refreshes allow us to reduce TPM load.

Add user agent considerations section

---

spec.bs

If the `continue` field is false, then all other fields are optional. Also, the `allowed_refresh_initiators` field is optional.

Update required fields in JSON session instruction format

---

spec.bs

Since `defer_requests` is not defined anywhere in the spec, it seems to have been unintentionally left in the example.
Following https://github.com/w3c/webappsec-dbsc/pull/121, the `defer_requests` field has been deleted.

Remove currently unused defer_requests field from the example

---

spec.bs

The current descriptions do not match the implementation or the JWT RFCs.

Update types of JWT fields

---

spec.bs

The public key itself is a possibly complex structure. RFC7638 provides a standard way to uniquely identify a key based on the SHA256 of a particular serialization of the JWK. That will also suffice for our purposes since it still proves knowledge of a high-entropy identifier.

Specify provider_keys are JWK thumbprints

---

spec.bs

If a subdomain tries to register a session for the entire site, we check a .well-known to ensure that it's permissible. In order to avoid latency on the hot path, we should not do that on refresh.

Do not check .well-known for refreshes

---

spec.bs

My understanding is that @kmonsen is no longer actively contributing to this specification, and that the affiliation with Google is outdated. Is this an accurate adjustment, @kmonsen, @drubery, and @thefrog-gh?

[Editorial] Shift Kristian Monsen to emeritus status.

---

spec.bs

Hey! We are implementing DBSC, and noticed that the example of `Secure-Session-Skipped` header is missing double quotes (`"`) around `session_identifier` parameters' values. Having double quotes there would be consistent with the spec's wording that value if supposed to be an `sf-string` as well as the actual headers we are observing:
> An [sf-parameter](https://datatracker.ietf.org/doc/html/rfc9651#name-parameters) whose key is "session_identifier", and whose value is an [sf-string](https://datatracker.ietf.org/doc/html/rfc9651#string), conveying the identifier of the skipped session.

Fix example of `Secure-Session-Skipped`

---

spec.bs

Address the feedback in https://github.com/w3c/webappsec-dbsc/issues/201, restricting the fields in JWTs. This also limits the risk of incorrect JWT validation by using a key in the JWT on refresh, or not checking that the "sub" claim matches the "Sec-Secure-Session-Id" header.

Update JWT format
